# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
warnings_are_errors: true

addons:
  apt:
    packages:
    - libfftw3-dev
    - devscripts

os:
  - linux
  - osx

r:
  - release
  - devel
  - oldrel


before_install:
  - fname=travis_helpers.sh
  - wget -O ${fname} http://bit.ly/travis_helpers
  - cat ${fname}; source ${fname}; rm ${fname}
  - cat DESCRIPTION
  - fftw_install ;

matrix:
  allow_failures:
    - r: devel
    - r: oldrel

r_packages:
  - covr

after_success:
  - Rscript -e 'covr::codecov(type = "all")'
